packages:
  - applications/*
  - packages/*
  - tooling/*

catalogMode: prefer

catalog:
  '@tanstack/eslint-plugin-query': 5.99.0
  '@tanstack/eslint-plugin-router': 1.161.6
  '@types/node': 24.12.2
  eslint-plugin-react-hooks-extra: 2.13.0
  eslint-plugin-react-naming-convention: 2.13.0
  eslint-plugin-react-web-api: 2.13.0
  oxfmt: 0.43.0
  oxlint: 1.58.0
  oxlint-tsgolint: 0.20.0
  typescript: 6.0.2
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
overrides:
  typescript: 'catalog:'
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
